# NumPy - Numerical Python

- A library of python
- Mostly used to work with Arrays in Python

In [ ]:
#importing numpy

import numpy as np

### Numpy Array (ndarray)

- NumPy provides a powerful and efficient way to work with arrays, especially for numerical data.
    - `Homogeneous`: All elements must be of the same data type, which improves performance.
    - `N-dimensional`: Supports multi-dimensional arrays (e.g., matrices).
    - `Vectorized Operations`: Allows for efficient mathematical operations on arrays without explicit loops.
    
Once created, the total size of the array can’t change.

### Numpy Array over Lists

In Python, we have lists that serve the purpose of arrays, but they are slow to process.
   - NumPy array is up to 50x faster than traditional Python lists.
   - NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

##### Creating a Numpy Array

In [ ]:
# From a Python list

np_array = np.array([1, 2, 3, 4, 5])
print(np_array)
type(np_array)

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

type(a)

In [ ]:
# From a Python list
np_array = np.array([1, 2, 3, 4, 5])

print(np_array)
type(np_array)

In [ ]:
# Array of zeros

zeros_array = np.zeros((3, 4))  # 3x4 array

print(zeros_array)
type(zeros_array)

In [ ]:
# Array of ones

ones_array = np.ones((2, 3))  # 2x3 array

print(ones_array)
type(ones_array)

In [ ]:
# Array of range

range_array = np.arange(6)
print(range_array)
type(ones_array)

### Dimensions in Arrays

##### 0-D arrays

In [ ]:
# 0-D arrays, or Scalars, are the elements in an array.
# Each value in an array is a 0-D array.

arr = np.array(42)

print(arr)

##### 1-D Arrays

In [ ]:
# An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

arr = np.array([1, 2, 3, 4, 5])

print(arr)

##### 2-D Arrays

In [ ]:
# An array that has 1-D arrays as its elements is called a 2-D array.

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

##### 3-D Arrays

In [ ]:
# An array that has 2-D arrays (matrices) as its elements is called 3-D array.

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

In [ ]:
#checking number of dimensions of an array

arr.ndim

##### Higher Dimensional Arrays

In [ ]:
# An array can have any number of dimensions.

arr = np.array([1, 2, 3, 4], ndmin=5) #ndimn to specify dimension of an array

print(arr)
print('number of dimensions :', arr.ndim)

In [ ]:
# ques

# do after learning how to access an array element 

# how to access element 3 from above array

arr[0,0,0,0,3]

##### Accessing Array Elements

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

In [ ]:
print(arr[1])

In [ ]:
print(arr[2] + arr[3]) #adding 2 elements of an array using indexing

###### Accessing 2-D arrays

- To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.
- Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('3rd element on 2st row: ', arr[1, 2])

In [ ]:
# ques 1 

# Access the element on the 1nd row, 5th column:



##### Access 3-D Arrays

- To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

##### Negative Indexing

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print (arr[-1, -1])

##### Alternate way of accessing elements in array

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print (arr[-2][-1])

In [ ]:
# ques 3

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(arr[1, 1, -1])

##### Numpy Array Slicing 

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

In [ ]:
# Slice elements from index 4 to the end of the array:

print(arr[4:])

In [ ]:
# Slice from the index 3 from the end to index 1 from the end:

print(arr[-3:-1])

### Datatypes in Array

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

In [ ]:
s='hi'
s = s.encode('utf-8')
print(s)

In [ ]:
#checking datatype of an array

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

In [ ]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

##### Creating Arrays With a Defined Data Type

In [ ]:
arr = np.array([-1, 2, -3, 4], dtype='u1')

print(arr)
print(arr.dtype)

For i, u, f, S and U we can define size as well.

In [ ]:
#An array with data type 4 bytes integer

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

In [ ]:
#ques 4

arr = np.array(['1', '2', '3'], dtype='i')
print(arr)
print(arr.dtype)

##### Converting Data Type on Existing Arrays

- The best way to change the data type of an existing array, is to make a copy of the array with the `astype()` method.

In [ ]:
# Change data type from float to integer by using 'i' as parameter value

arr = np.array([1.1, 2.1, 3.9])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

In [ ]:
# ques 5

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

In [ ]:
# ques 6

arr = np.array([-1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

### Copying and View

In [ ]:
# Copy

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

In [ ]:
# View

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

In [ ]:
# ques 6

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

In [ ]:
# base attribute - checks array is on its own or refers to the original object

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

### Shape of an Array

- The shape of an array is the number of elements in each dimension.
- NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

In [ ]:
# ques 7

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)

### Reshaping arrays

- By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [ ]:
# Reshape From 1-D to 2-D

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

In [ ]:
# Reshape From 1-D to 3-D

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

In [ ]:
# ques 7

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)

print(newarr)

In [ ]:
# Check if the returned array is a copy or a view

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

##### Unknown Dimension

- We do not have to specify an exact number for one of the dimensions in the reshape method.
- Pass -1 as the value, and NumPy will calculate this number for you.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, -1)

print(newarr)

In [ ]:
# ques 8

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, -1, -1)

print(newarr)

`We can not pass -1 to more than one dimension.`

In [ ]:
# ques 9

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

`The above concept is called flattening of any array`

### Iterating Arrays

In [ ]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

##### Iterating 2-D Arrays

In [ ]:
# Iterate on the elements of the following 2-D array:

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

In [ ]:
# Iterate on each scalar element of the 2-D array:

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

##### Iterating 3-D Arrays

In [ ]:
# Iterate on the elements of the following 3-D array:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

In [ ]:
# Iterate down to the scalars:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

##### Iterating Arrays Using nditer()

In [ ]:
#Iterating on Each Scalar Element

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

In [ ]:
# Iterating Array With Different Data Types

import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

In [ ]:
# Iterating With Different Step Size

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

In [426]:
# Enumerated Iteration Using ndenumerate()

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [427]:
# Enumerate on following 2D array's elements:

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


### Joining NumPy Arrays

- Joining means putting contents of two or more arrays in a single array
- NumPy we join arrays by axes
- We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

##### Joining Arrays Using Concatenate

In [428]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[1 2 3 4 5 6]


In [429]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


##### Joining Arrays Using Stack Functions

- Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

In [430]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [431]:
# hstack() to stack along rows.

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [432]:
# vstack()  to stack along columns.

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [433]:
# dstack() to stack along height, which is the same as depth.

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


### Splitting NumPy Arrays

- Splitting is reverse operation of Joining.
- Joining merges multiple arrays into one and Splitting breaks one array into multiple.
- We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [434]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [435]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [436]:
#using split function

xarr = np.array([1, 2, 3, 4, 5, 6, 7])

newarr = np.split(xarr, 4)

print(newarr)

ValueError: array split does not result in an equal division

In [437]:
# accessing splited arrays

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [438]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [439]:
# An alternate solution is using hsplit() opposite of hstack()

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


### Searching Arrays

- You can search an array for a certain value, and return the indexes that get a match.
- To search an array, use the where() method.

In [440]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [ ]:
np.where(arr == 4)

In [441]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


##### Search Sorted

There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

In [442]:
arr = np.array([6, 7, 9, 10])

x = np.searchsorted(arr, 8)

print(x)

2


In [443]:
# ques

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


##### Search From the Right Side
By default the left most index is returned, but we can give side='right' to return the right most index instead.

In [444]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


### Sorting Arrays

- The NumPy ndarray object has a function called sort(), that will sort a specified array.
- This method returns a copy of the array, leaving the original array unchanged.

In [445]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [446]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [447]:

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


##### Sorting a 2-D Array

In [448]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


### Filtering Arrays

In [449]:
#Using boolean index list

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [ ]:
# Creating the Filter Array

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

In [ ]:
# Create a filter array that will return only even elements from the original array

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

##### Creating Filter Directly From Array

In [450]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [451]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


### Random Numbers in NumPy

In [492]:
# Generate a random integer from 0 to 100:

x = np.random.randint(10)

print(x)

5


In [480]:
# Generate a random float from 0 to 1:

x = np.random.rand()

print(x)

0.6898005584064433


##### Generate Random Array

The randint() method takes a size parameter where you can specify the shape of an array.

In [505]:
x = np.random.randint(100, size=(5))

print(x)

[23 94 25 25 52]


In [506]:
# Generating 2-D random arrays

x = np.random.randint(100, size=(3, 5))

print(x)


[[84 85  9 10 48]
 [74 24 58 43 27]
 [36 34  7 15 71]]


In [507]:
# ques 8

x = np.random.rand(3, 5)

print(x)

[[0.81387052 0.06299836 0.04177378 0.33309998 0.10299085]
 [0.35489152 0.61131406 0.79022588 0.94596629 0.07644873]
 [0.95043253 0.11546397 0.80435382 0.72335033 0.70633874]]


##### Generate Random Number From Array

- choice() method allows you to generate a random value based on an array of values.
- It takes an array as a parameter and randomly returns one of the values.

In [530]:
x = np.random.choice([3, 5, 7, 9])

print(x)

7


- It also allows you to return an array of values.
- Add a size parameter to specify the shape of the array.

In [ ]:
# creating a 2-D array using choice

x = np.random.choice([3, 5, 7, 9], size=(3, 5))

print(x)